[package]
name = "she"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["cdylib"]

[dependencies]
num = "0.4.0"
rand = "0.8.0"
wasm-bindgen = "0.2.79"
getrandom = { version = "0.2", features = ["js"] }

# wgpu dependencies
image = "0.23"
winit = "0.26"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }